from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import pandas as pd
import json

def get_restaurant_data(url):
    # Initialize WebDriver using webdriver-manager
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service)
    
    # Set a reasonable timeout for loading the page
    driver.set_page_load_timeout(30)
    
    try:
        driver.get(url)
    except TimeoutException:
        print(f"Page load timed out for {url}.")
        driver.quit()
        return {}
    
    # Use a more general approach to wait for recognizable content
    try:
        WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.TAG_NAME, 'body'))  # Waiting for the body tag as a general indicator
        )
    except TimeoutException:
        print(f"Elements took too long to load for {url}.")
        driver.quit()
        return {}
    
    # Get the fully rendered page source
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    
    # Extract restaurant data
    data = {}
    try:
        # Extract information from the page
        name = soup.find('meta', {'property': 'og:title'})['content']
        description = soup.find('meta', {'name': 'description'})['content']
        image_url = soup.find('meta', {'property': 'og:image'})['content']
        phone = None
        
        # Extract phone number from structured data
        scripts = soup.find_all('script', type='application/ld+json')
        for script in scripts:
            if '"telephone"' in script.text:
                phone = json.loads(script.text).get('telephone', None)
                
        # Extract reviews, cuisine, and other information
        aggregate_rating = None
        reviews_count = None
        cuisine = None
        
        # Extract aggregate rating
        for script in scripts:
            if '"aggregateRating"' in script.text:
                data_json = json.loads(script.text)
                aggregate_rating = data_json.get('aggregateRating', {}).get('ratingValue', None)
                reviews_count = data_json.get('aggregateRating', {}).get('ratingCount', None)
                
        # Extract cuisine
        for script in scripts:
            if '"servesCuisine"' in script.text:
                data_json = json.loads(script.text)
                cuisine = data_json.get('servesCuisine', None)
        
        data['name'] = name
        data['description'] = description
        data['image_url'] = image_url
        data['phone'] = phone
        data['aggregate_rating'] = aggregate_rating
        data['reviews_count'] = reviews_count
        data['cuisine'] = cuisine
        
    except Exception as e:
        print(f"Error extracting data from {url}: {e}")
    
    driver.quit()
    return data

# List of restaurant URLs to scrape
restaurant_urls = [
   "https://www.zomato.com/ahmedabad/foo-ahmedabad-3-thaltej/info",
"https://www.zomato.com/ahmedabad/makeba-the-lounge-cafe-vastrapur/info",
"https://www.zomato.com/ahmedabad/1989-by-sphere-lounge-ambavadi/info",
"https://www.zomato.com/ahmedabad/mrs-mage-hyatt-ahmedabad-vastrapur/info",
"https://www.zomato.com/ahmedabad/r-kitchen-renaissance-hotel-sola/info",
"https://www.zomato.com/ahmedabad/saffron-gurukul/info",
"https://www.zomato.com/ahmedabad/tinello-hyatt-regency-ashram-road/info",
"https://www.zomato.com/ahmedabad/topspin-bodakdev/info",
"https://www.zomato.com/ahmedabad/china-house-hyatt-regency-ashram-road/info",
"https://www.zomato.com/ahmedabad/punjab-grill-thaltej/info",
"https://www.zomato.com/ahmedabad/aura-courtyard-by-marriott-sbr-bodakdev/info",
"https://www.zomato.com/ahmedabad/three-quarter-indian-satellite/info",
"https://www.zomato.com/ahmedabad/the-house-of-makeba-bodakdev/info",
"https://www.zomato.com/ahmedabad/1980-a-royal-culinary-experience-bodakdev/info",
"https://www.zomato.com/ahmedabad/table-tales-bodakdev/info",
"https://www.zomato.com/ahmedabad/chilis-grill-bar-vastrapur/info",
"https://www.zomato.com/ahmedabad/welcomcafe-ikkat-ashram-road/info",
"https://www.zomato.com/ahmedabad/lithosphere-by-upper-crust-bodakdev/info",
"https://www.zomato.com/ahmedabad/nomad-pizza-c-g-road/info",
"https://www.zomato.com/ahmedabad/silver-leaf-thaltej/info",
"https://www.zomato.com/ahmedabad/unlocked-navrangpura/info",
"https://www.zomato.com/ahmedabad/tres-amigos-thaltej/info",
"https://www.zomato.com/ahmedabad/amritsar-haveli-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/banjara-the-culinary-symphony-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/bellasen-bistro-bodakdev/info",
"https://www.zomato.com/ahmedabad/masala-county-chandkheda/info",
"https://www.zomato.com/ahmedabad/tg-s-the-oriental-grill-hyatt-vastrapur/info",
"https://www.zomato.com/ahmedabad/angithi-a-pure-veg-restaurant-by-mirch-masala-bodakdev/info",
"https://www.zomato.com/ahmedabad/sams-pizza-navrangpura/info",
"https://www.zomato.com/ahmedabad/the-messy-door-cafe-navrangpura/info",
"https://www.zomato.com/ahmedabad/the-secret-kitchen-bodakdev/info",
"https://www.zomato.com/ahmedabad/rustic-spices-satellite/info",
"https://www.zomato.com/ahmedabad/food-stories-by-the-westend-thaltej/info",
"https://www.zomato.com/ahmedabad/the-barnyard-co-chandkheda/info",
"https://www.zomato.com/ahmedabad/kake-di-hatti-bodakdev/info",
"https://www.zomato.com/ahmedabad/ishaara-thaltej/info",
"https://www.zomato.com/ahmedabad/elolivo-sbr-thaltej/info",
"https://www.zomato.com/ahmedabad/tim-tim-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/scobys-c-g-road/info",
"https://www.zomato.com/ahmedabad/pepito-thaltej/info",
"https://www.zomato.com/ahmedabad/cafe-patio-hotel-binori-thaltej/info",
"https://www.zomato.com/ahmedabad/sankalp-signature-bodakdev/info",
"https://www.zomato.com/ahmedabad/harmony-resto-cafe-navrangpura/info",
"https://www.zomato.com/ahmedabad/the-fountain-chandkheda/info",
"https://www.zomato.com/ahmedabad/oaxaca-navrangpura/info",
"https://www.zomato.com/ahmedabad/varietea-bodakdev/info",
"https://www.zomato.com/ahmedabad/pizza-don-navrangpura/info",
"https://www.zomato.com/ahmedabad/citrus-junction-the-leela-sector-16-gandhinagar/info",
"https://www.zomato.com/ahmedabad/kith-kin-coffee-and-more-thaltej/info",
"https://www.zomato.com/ahmedabad/sazzy-sizzlers-naranpura/info",
"https://www.zomato.com/ahmedabad/fashiontv-cafe-thaltej/info",
"https://www.zomato.com/ahmedabad/ks-charcoal-bodakdev/info",
"https://www.zomato.com/ahmedabad/chur-chur-naan-punjab-junction-gulbai-tekra/info",
"https://www.zomato.com/ahmedabad/cucina-restaurant-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/massala-theoryy-bodakdev/info",
"https://www.zomato.com/ahmedabad/patang-the-revolving-restaurant-ashram-road/info",
"https://www.zomato.com/ahmedabad/pizzaiiolo-the-wood-fired-pizza-thaltej/info",
"https://www.zomato.com/ahmedabad/ree-story-thaltej/info",
"https://www.zomato.com/ahmedabad/volga-restaurant-bhadra/info",
"https://www.zomato.com/ahmedabad/the-vibe-x-restro-cafe-chandkheda/info",
"https://www.zomato.com/ahmedabad/zoca-cafe-bodakdev/info",
"https://www.zomato.com/ahmedabad/cilantros-global-cuisine-restaurant-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/m-a-d-by-tomatos-bodakdev/info",
"https://www.zomato.com/ahmedabad/mahamahal-thaltej/info",
"https://www.zomato.com/ahmedabad/chelvies-coffee-bodakdev/info",
"https://www.zomato.com/ahmedabad/mayka-bodakdev/info",
"https://www.zomato.com/ahmedabad/kuro-renaissance-hotel-sola/info",
"https://www.zomato.com/ahmedabad/the-shaka-cafe-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/dakshin-bhojnam-1-sola/info",
"https://www.zomato.com/ahmedabad/govindas-1-satellite/info",
"https://www.zomato.com/ahmedabad/cafe-street-circus-by-tqi-thaltej/info",
"https://www.zomato.com/ahmedabad/tim-tim-brew-house-bodakdev/info",
"https://www.zomato.com/ahmedabad/koffee-stories-ambavadi/info",
"https://www.zomato.com/ahmedabad/rustic-rays-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/cha-1-thaltej/info",
"https://www.zomato.com/ahmedabad/kaffa-coffee-roasters-vastrapur/info",
"https://www.zomato.com/ahmedabad/jajarmaan-thaltej/info",
"https://www.zomato.com/ahmedabad/from-the-north-c-g-road/info",
"https://www.zomato.com/ahmedabad/wow-dosa-fusion-of-south-indian-food-gurukul/info",
"https://www.zomato.com/ahmedabad/burma-burma-thaltej/info",
"https://www.zomato.com/ahmedabad/pomodoro-bodakdev/info",
"https://www.zomato.com/ahmedabad/pol-21-hotel-binori-thaltej/info",
"https://www.zomato.com/ahmedabad/varietea-chai-masti-more-sola/info",
"https://www.zomato.com/ahmedabad/pep-house-bodakdev/info",
"https://www.zomato.com/ahmedabad/cocoa-drama-bodakdev/info",
"https://www.zomato.com/ahmedabad/@mango-bodakdev/info",
"https://www.zomato.com/ahmedabad/jalpaan-restaurant-thaltej/info",
"https://www.zomato.com/ahmedabad/upper-crust-navrangpura/info",
"https://www.zomato.com/ahmedabad/wok-on-fire-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/roastery-cultur-the-coffee-company-bodakdev/info",
"https://www.zomato.com/ahmedabad/mirch-masala-bodakdev/info",
"https://www.zomato.com/ahmedabad/ukiyo-live-in-the-moment-1-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/casaro-fromagerie-deli-thaltej/info",
"https://www.zomato.com/ahmedabad/the-masala-stories-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/di-grano-hot-fresh-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/vintage-vibes-thaltej/info",
"https://www.zomato.com/ahmedabad/poult-thaltej/info",
"https://www.zomato.com/ahmedabad/roast-toast-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/caffe-allora-thaltej/info",
"https://www.zomato.com/ahmedabad/java-courtyard-by-marriott-satellite/info",
"https://www.zomato.com/ahmedabad/urban-zykaa-mani-nagar/info",
"https://www.zomato.com/ahmedabad/temptations-the-eatery-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/shree-annapurna-corner-1-mani-nagar/info",
"https://www.zomato.com/ahmedabad/the-square-hotel-novotel-satellite/info",
"https://www.zomato.com/ahmedabad/silver-leaf-cama-hotel-lal-darwaja/info",
"https://www.zomato.com/ahmedabad/nook-by-grace-coffee-co-navrangpura/info",
"https://www.zomato.com/ahmedabad/nosh-2-thaltej/info",
"https://www.zomato.com/ahmedabad/mocha-bodakdev/info",
"https://www.zomato.com/ahmedabad/la-shanti-bodakdev/info",
"https://www.zomato.com/ahmedabad/cafezza-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/sizzling-shihai-chandkheda/info",
"https://www.zomato.com/ahmedabad/gordhan-thaal-satellite/info",
"https://www.zomato.com/ahmedabad/sphere-lounge-hotel-ramada-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/grilled-baked-boiled-restaurant-bopal/info",
"https://www.zomato.com/ahmedabad/saffron-restaurant-ramada-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/grill-kitchen-chandkheda/info",
"https://www.zomato.com/ahmedabad/brick-kitchen-five-petals-ghatlodia/info",
"https://www.zomato.com/ahmedabad/micro-cafe-bodakdev/info",
"https://www.zomato.com/ahmedabad/little-french-house-navrangpura/info",
"https://www.zomato.com/ahmedabad/diya-the-leela-sector-16-gandhinagar/info",
"https://www.zomato.com/ahmedabad/ninis-kitchen-c-g-road/info",
"https://www.zomato.com/ahmedabad/taam-jhaam-bodakdev/info",
"https://www.zomato.com/ahmedabad/zeus-a-creative-fleet-restro-chandkheda/info",
"https://www.zomato.com/ahmedabad/the-half-story-chandkheda/info",
"https://www.zomato.com/ahmedabad/the-indian-channel-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/collage-hyatt-vastrapur/info",
"https://www.zomato.com/ahmedabad/moksha-lounge-the-leela-sector-16-gandhinagar/info",
"https://www.zomato.com/ahmedabad/lollo-rosso-bodakdev/info",
"https://www.zomato.com/ahmedabad/amala-bodakdev/info",
"https://www.zomato.com/ahmedabad/narayani-multicuisine-restaurant-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/acchija-the-kachchhi-gujarati-thal-bodakdev/info",
"https://www.zomato.com/ahmedabad/temptt-restro-and-cafe-chandkheda/info",
"https://www.zomato.com/ahmedabad/peppers-by-pepperazzi-c-g-road/info",
"https://www.zomato.com/ahmedabad/kovallam-c-g-road/info",
"https://www.zomato.com/ahmedabad/the-bawa-bistro-navrangpura/info",
"https://www.zomato.com/ahmedabad/yanki-sizzlerr-navrangpura/info",
"https://www.zomato.com/ahmedabad/shararat-bodakdev/info",
"https://www.zomato.com/ahmedabad/ftv-cafe-restro-thaltej/info",
"https://www.zomato.com/ahmedabad/cabana-thaltej/info",
"https://www.zomato.com/ahmedabad/mill-co-renaissance-hotel-sola/info",
"https://www.zomato.com/ahmedabad/terracotta-4-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/1944-the-hocco-kitchen-navrangpura/info",
"https://www.zomato.com/ahmedabad/sale-and-pepe-ristorante-italiano-ambavadi/info",
"https://www.zomato.com/ahmedabad/hocco-eatery-satellite/info",
"https://www.zomato.com/ahmedabad/neem-county-bodakdev/info",
"https://www.zomato.com/ahmedabad/trevi-the-hillock-adalaj/info",
"https://www.zomato.com/ahmedabad/gwalbhog-bodakdev/info",
"https://www.zomato.com/ahmedabad/dosbros-fresh-mexican-grill-thaltej/info",
"https://www.zomato.com/ahmedabad/the-penthouse-chapter-one-by-novelchef-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/real-xpresso-2-sola/info",
"https://www.zomato.com/ahmedabad/mauve-thaltej/info",
"https://www.zomato.com/ahmedabad/wave-double-tree-by-hilton-bopal/info",
"https://www.zomato.com/ahmedabad/kaffee-mast-hai-chandkheda/info",
"https://www.zomato.com/ahmedabad/agashiye-the-house-of-mg-lal-darwaja/info",
"https://www.zomato.com/ahmedabad/peshawri-itc-narmada-1-vastrapur/info",
"https://www.zomato.com/ahmedabad/the-pink-door-restaurant-gandhinagar-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/timpani-radisson-blu-ambavadi/info",
"https://www.zomato.com/ahmedabad/sip-of-hope-the-coffee-house-2-bodakdev/info",
"https://www.zomato.com/ahmedabad/aagrah-chandkheda/info",
"https://www.zomato.com/ahmedabad/roastea-cafe-bopal/info",
"https://www.zomato.com/ahmedabad/exquisitto-1-vastrapur/info",
"https://www.zomato.com/ahmedabad/650-the-global-kitchen-ambavadi/info",
"https://www.zomato.com/ahmedabad/cream-centre-bodakdev/info",
"https://www.zomato.com/ahmedabad/kanchiipuram-bodakdev/info",
"https://www.zomato.com/ahmedabad/grubous-bodakdev/info",
"https://www.zomato.com/ahmedabad/dosawala-thaltej/info",
"https://www.zomato.com/ahmedabad/momo-café-courtyard-by-marriott-satellite/info",
"https://www.zomato.com/ahmedabad/dakshini-24-bopal/info",
"https://www.zomato.com/ahmedabad/maeva-restaurant-banquet-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/z27-coffee-bar-thaltej/info",
"https://www.zomato.com/ahmedabad/kitcha-1-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/the-chocolate-room-diner-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/mleko-navrangpura/info",
"https://www.zomato.com/ahmedabad/eat-punjab-chandkheda/info",
"https://www.zomato.com/ahmedabad/pemdora-the-planet-of-food-dessert-sola/info",
"https://www.zomato.com/ahmedabad/dine-9-multicuisine-restaurant-vastrapur/info",
"https://www.zomato.com/ahmedabad/compass-kitchen-2-chandkheda/info",
"https://www.zomato.com/ahmedabad/ramodi-kitchen-by-rasna-bopal/info",
"https://www.zomato.com/ahmedabad/dine-in-the-clouds-thaltej/info",
"https://www.zomato.com/ahmedabad/umami-by-curries-vastrapur/info",
"https://www.zomato.com/ahmedabad/iscon-thal-satellite/info",
"https://www.zomato.com/ahmedabad/jugmug-thela-thaltej/info",
"https://www.zomato.com/ahmedabad/niro-by-ninis-gulbai-tekra/info",
"https://www.zomato.com/ahmedabad/cafe-de-italiano-bodakdev/info",
"https://www.zomato.com/ahmedabad/southern-express-bopal/info",
"https://www.zomato.com/ahmedabad/shivahu-ambavadi/info",
"https://www.zomato.com/ahmedabad/the-trophy-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/sarvatt-hyatt-regency-ashram-road/info",
"https://www.zomato.com/ahmedabad/muse-bodakdev/info",
"https://www.zomato.com/ahmedabad/barbeque-nation-vastrapur/info",
"https://www.zomato.com/ahmedabad/papadum-thaltej/info",
"https://www.zomato.com/ahmedabad/artisan-regenta-antarim-navrangpura/info",
"https://www.zomato.com/ahmedabad/poetry-8-bodakdev/info",
"https://www.zomato.com/ahmedabad/mynt-vivanta-sola/info",
"https://www.zomato.com/ahmedabad/arbre-satellite/info",
"https://www.zomato.com/ahmedabad/legends-of-punjab-by-pepperazi-bodakdev/info",
"https://www.zomato.com/ahmedabad/jassi-de-parathe-odhav/info",
"https://www.zomato.com/ahmedabad/gourmet-kitchen-maple-99-chandkheda/info",
"https://www.zomato.com/ahmedabad/big-scoop-cafe-ashram-road/info",
"https://www.zomato.com/ahmedabad/sankalp-c-g-road/info",
"https://www.zomato.com/ahmedabad/the-greenstraw-house-ashram-road/info",
"https://www.zomato.com/ahmedabad/the-eatery-four-points-by-sheraton-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/gwalia-vanakkam-thaltej/info",
"https://www.zomato.com/ahmedabad/jamie-oliver-kitchen-thaltej/info",
"https://www.zomato.com/ahmedabad/hocco-eatery-1-bopal/info",
"https://www.zomato.com/ahmedabad/a-gourmesserie-bodakdev/info",
"https://www.zomato.com/ahmedabad/yukki-sizzler-sola/info",
"https://www.zomato.com/ahmedabad/burnt-turnt-bopal/info",
"https://www.zomato.com/ahmedabad/carry-on-tomatos-mirch-masala-bopal/info",
"https://www.zomato.com/ahmedabad/rangeen-ambavadi/info",
"https://www.zomato.com/ahmedabad/crazy-plant-lady-a-plant-boutique-cafe-nava-vadaj/info",
"https://www.zomato.com/ahmedabad/cuppuccino-navrangpura/info",
"https://www.zomato.com/ahmedabad/cafe-treat-the-pride-hotel-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-great-kabab-factory-radisson-blu-ambavadi/info",
"https://www.zomato.com/ahmedabad/soul-square-bodakdev/info",
"https://www.zomato.com/ahmedabad/essence-crowne-plaza-satellite/info",
"https://www.zomato.com/ahmedabad/masala-maarke-6-sola/info",
"https://www.zomato.com/ahmedabad/momoman-4-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/cream-centre-thaltej/info",
"https://www.zomato.com/ahmedabad/kfc-vastrapur/info",
"https://www.zomato.com/ahmedabad/rooh-the-roofyard-cafe-and-restaurant-karai-gandhinagar/info",
"https://www.zomato.com/ahmedabad/florence-at-nine-bopal/info",
"https://www.zomato.com/ahmedabad/cafe-tt-chandkheda/info",
"https://www.zomato.com/ahmedabad/indus-vivanta-sola/info",
"https://www.zomato.com/ahmedabad/maha-mahim-bopal/info",
"https://www.zomato.com/ahmedabad/novelchef-cafe-lounge-gulbai-tekra/info",
"https://www.zomato.com/ahmedabad/chinese-wok-c-g-road/info",
"https://www.zomato.com/ahmedabad/bento-b-japanese-diner-bopal/info",
"https://www.zomato.com/ahmedabad/the-gourmet-an-all-day-dining-restaurant-by-the-fern-residency-subhash-bridge/info",
"https://www.zomato.com/ahmedabad/hoglatto-1-ambavadi/info",
"https://www.zomato.com/ahmedabad/gwalia-purani-delhi-bopal/info",
"https://www.zomato.com/ahmedabad/sante-spa-cuisine-thaltej/info",
"https://www.zomato.com/ahmedabad/choice-snack-bar-1-memnagar/info",
"https://www.zomato.com/ahmedabad/rooftop-stories-thaltej/info",
"https://www.zomato.com/ahmedabad/naivedhyam-thal-satellite/info",
"https://www.zomato.com/ahmedabad/curries-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/sambar-cafe-bodakdev/info",
"https://www.zomato.com/ahmedabad/maharaja-manek-chowkwala-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/mexicano-by-the-bay-ashram-road/info",
"https://www.zomato.com/ahmedabad/octant-pizza-c-g-road/info",
"https://www.zomato.com/ahmedabad/wow-china-isanpur/info",
"https://www.zomato.com/ahmedabad/cafe-piano-the-grand-bhagwati-bodakdev/info",
"https://www.zomato.com/ahmedabad/twenty-1-rhinos-1-chandkheda/info",
"https://www.zomato.com/ahmedabad/vintage-village-naroda/info",
"https://www.zomato.com/ahmedabad/hungry-puppet-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/dakshination-mani-nagar/info",
"https://www.zomato.com/ahmedabad/the-lifafa-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/micro-cafe-memnagar/info",
"https://www.zomato.com/ahmedabad/wow-momo-isanpur/info",
"https://www.zomato.com/ahmedabad/orchid-by-fortune-inn-haveli-sector-11-gandhinagar/info",
"https://www.zomato.com/ahmedabad/jail-cafe-bar-navrangpura/info",
"https://www.zomato.com/ahmedabad/cafe-alaska-thaltej/info",
"https://www.zomato.com/ahmedabad/baba-budan-cafe-sola/info",
"https://www.zomato.com/ahmedabad/spice-hub-restro-cafe-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/megma-restaurant-banquets-1-odhav/info",
"https://www.zomato.com/ahmedabad/brooks-tragad/info",
"https://www.zomato.com/ahmedabad/tandoor-story-chur-chur-naan-bodakdev/info",
"https://www.zomato.com/ahmedabad/barbeque-world-vastrapur/info",
"https://www.zomato.com/ahmedabad/green-house-the-house-of-mg-lal-darwaja/info",
"https://www.zomato.com/ahmedabad/south-leaf-the-food-chain-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/silver-dine-platinum-hotels-paldi/info",
"https://www.zomato.com/ahmedabad/the-starry-foliage-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/thepla-junction-1-c-g-road/info",
"https://www.zomato.com/ahmedabad/altitude-the-rooftop-by-upper-crust-bodakdev/info",
"https://www.zomato.com/ahmedabad/swati-snacks-c-g-road/info",
"https://www.zomato.com/ahmedabad/shamiana-by-taj-skyline-bodakdev/info",
"https://www.zomato.com/ahmedabad/subway-1-bopal/info",
"https://www.zomato.com/ahmedabad/mad-over-grills-thaltej/info",
"https://www.zomato.com/ahmedabad/vadilal-now-for-ever-bodakdev/info",
"https://www.zomato.com/ahmedabad/bluez-terrace-cafe-c-g-road/info",
"https://www.zomato.com/ahmedabad/the-grill-street-satellite/info",
"https://www.zomato.com/ahmedabad/arsa-bopal/info",
"https://www.zomato.com/ahmedabad/pepper-fusion-1-thaltej/info",
"https://www.zomato.com/ahmedabad/roastea-1-vastrapur/info",
"https://www.zomato.com/ahmedabad/the-chocolate-room-1-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/marky-momos-chandkheda/info",
"https://www.zomato.com/ahmedabad/rasa-restro-cafe-adalaj/info",
"https://www.zomato.com/ahmedabad/huber-holly-1-bopal/info",
"https://www.zomato.com/ahmedabad/turquoise-villa-vastrapur/info",
"https://www.zomato.com/ahmedabad/coffee-culture-thaltej/info",
"https://www.zomato.com/ahmedabad/la-milano-pizzeria-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/desi-rasoi-satellite/info",
"https://www.zomato.com/ahmedabad/eatamins-chandkheda/info",
"https://www.zomato.com/ahmedabad/rangderi-karai-gandhinagar/info",
"https://www.zomato.com/ahmedabad/tab-brewing-co-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-indian-heat-ambavadi/info",
"https://www.zomato.com/ahmedabad/goyaa-the-bake-house-bodakdev/info",
"https://www.zomato.com/ahmedabad/bayleaf-courtyard-by-marriott-satellite/info",
"https://www.zomato.com/ahmedabad/vishalla-vasna/info",
"https://www.zomato.com/ahmedabad/dravida-fortune-select-sola/info",
"https://www.zomato.com/ahmedabad/core-the-coffee-shop-@-lithosphere-2-bodakdev/info",
"https://www.zomato.com/ahmedabad/hungry-horse-cafe-restro-1-bopal/info",
"https://www.zomato.com/ahmedabad/taste-tales-multicuisine-restaurant-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/tummy-bites-1-mani-nagar/info",
"https://www.zomato.com/ahmedabad/ristretto-behind-the-rods-navrangpura/info",
"https://www.zomato.com/ahmedabad/desi-bites-1-naroda/info",
"https://www.zomato.com/ahmedabad/radhikas-authentic-south-indian-food-gurukul/info",
"https://www.zomato.com/ahmedabad/shake-adda-naranpura/info",
"https://www.zomato.com/ahmedabad/vamjas-gota/info",
"https://www.zomato.com/ahmedabad/gallops-eateria-bopal/info",
"https://www.zomato.com/ahmedabad/the-cookie-co-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/urban-khichdi-vastrapur/info",
"https://www.zomato.com/ahmedabad/angat-22-the-restaurant-banquet-bopal/info",
"https://www.zomato.com/ahmedabad/wow-china-diner-thaltej/info",
"https://www.zomato.com/ahmedabad/air-bistro-bodakdev/info",
"https://www.zomato.com/ahmedabad/big-belly-burger-1-isanpur/info",
"https://www.zomato.com/ahmedabad/bubblepop-thaltej/info",
"https://www.zomato.com/ahmedabad/uboat-gourmet-subs-navrangpura/info",
"https://www.zomato.com/ahmedabad/bleu-9-patisserie-thaltej/info",
"https://www.zomato.com/ahmedabad/bhookh-lagi-hai-satellite/info",
"https://www.zomato.com/ahmedabad/happy-hour-veg-bbq-tandoor-1-paldi/info",
"https://www.zomato.com/ahmedabad/rooted-raws-5-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/bowl-story-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-blue-oven-bodakdev/info",
"https://www.zomato.com/ahmedabad/better-beans-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/ripples-avalon-hotel-bodakdev/info",
"https://www.zomato.com/ahmedabad/cafe-1st-story-fairfield-by-marriott-ashram-road/info",
"https://www.zomato.com/ahmedabad/poptos-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-mad-house-café-gulbai-tekra/info",
"https://www.zomato.com/ahmedabad/neem-chowk-bodakdev/info",
"https://www.zomato.com/ahmedabad/aambli-restaurant-banquets-nikol/info",
"https://www.zomato.com/ahmedabad/Southern-India/info",
"https://www.zomato.com/ahmedabad/gormoh-bodakdev/info",
"https://www.zomato.com/ahmedabad/amritsar-punjab-paratha-vastrapur/info",
"https://www.zomato.com/ahmedabad/blockheads-plates-playlists-bodakdev/info",
"https://www.zomato.com/ahmedabad/gl-dalwada-centre-navrangpura/info",
"https://www.zomato.com/ahmedabad/starbucks-coffee-c-g-road/info",
"https://www.zomato.com/ahmedabad/pizza-hut-nikol/info",
"https://www.zomato.com/ahmedabad/the-grand-thakar-satellite/info",
"https://www.zomato.com/ahmedabad/cafe-de-food-couture-1-bopal/info",
"https://www.zomato.com/ahmedabad/sizzling-mania-navrangpura/info",
"https://www.zomato.com/ahmedabad/earthen-oven-fortune-landmark-ashram-road/info",
"https://www.zomato.com/ahmedabad/the-orchid-odhav/info",
"https://www.zomato.com/ahmedabad/boji-cafe-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/d-caf-c-g-road/info",
"https://www.zomato.com/ahmedabad/dakshini-24-bodakdev/info",
"https://www.zomato.com/ahmedabad/mr-mrs-somani-the-grand-bhagwati-bodakdev/info",
"https://www.zomato.com/ahmedabad/riverside-deli-1-ashram-road/info",
"https://www.zomato.com/ahmedabad/leaf-restaurant-ashram-road/info",
"https://www.zomato.com/ahmedabad/atithi-bodakdev/info",
"https://www.zomato.com/ahmedabad/hl-frankie-navrangpura/info",
"https://www.zomato.com/ahmedabad/amritsari-kulcha-express-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/oozey-thaltej/info",
"https://www.zomato.com/ahmedabad/taco-bell-vastrapur/info",
"https://www.zomato.com/ahmedabad/jay-bhavani-fast-food-thaltej/info",
"https://www.zomato.com/ahmedabad/salad-time-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/wind-water-fortune-landmark-ashram-road/info",
"https://www.zomato.com/ahmedabad/the-project-cafe/info",
"https://www.zomato.com/ahmedabad/mainland-china-satellite/info",
"https://www.zomato.com/ahmedabad/rageez-bopal/info",
"https://www.zomato.com/ahmedabad/kurry-karamat-chandkheda/info",
"https://www.zomato.com/ahmedabad/the-potesta-restaurant-nikol/info",
"https://www.zomato.com/ahmedabad/dheemi-aanch-bodakdev/info",
"https://www.zomato.com/ahmedabad/piquant-thaltej/info",
"https://www.zomato.com/ahmedabad/the-peacock-restaurant-1-vatva/info",
"https://www.zomato.com/ahmedabad/kamala-cafe-bodakdev/info",
"https://www.zomato.com/ahmedabad/page-one-2-vastrapur/info",
"https://www.zomato.com/ahmedabad/super-donuts-american-eatery-bakery-gulbai-tekra/info",
"https://www.zomato.com/ahmedabad/chinese-wok-express-bodakdev/info",
"https://www.zomato.com/ahmedabad/cafe-where-we-meet-memnagar/info",
"https://www.zomato.com/ahmedabad/oven-the-bakery-cafe-gota/info",
"https://www.zomato.com/ahmedabad/kesar-the-ummed-hansol/info",
"https://www.zomato.com/ahmedabad/south-valley-vejalpur/info",
"https://www.zomato.com/ahmedabad/harshus-late-night-munchies-bopal/info",
"https://www.zomato.com/ahmedabad/rajwadu-vejalpur/info",
"https://www.zomato.com/ahmedabad/dakshinayan-navrangpura/info",
"https://www.zomato.com/ahmedabad/epicurean-alley-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/shree-om-banna-farsan-nikol/info",
"https://www.zomato.com/ahmedabad/myos-naranpura/info",
"https://www.zomato.com/ahmedabad/the-poutinerie-thaltej/info",
"https://www.zomato.com/ahmedabad/spiceville-by-hotel-nalanda-navrangpura/info",
"https://www.zomato.com/ahmedabad/tero-restro-cafe-1-thaltej/info",
"https://www.zomato.com/ahmedabad/rasilas-kitchen-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-food-drama-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/sadak-chaap-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/new-mehfil-restaurant-shahpur/info",
"https://www.zomato.com/ahmedabad/la-festiva-restaurant-banquet-1-sola/info",
"https://www.zomato.com/ahmedabad/lunaris-naranpura/info",
"https://www.zomato.com/ahmedabad/aura-the-restaurant-chandkheda/info",
"https://www.zomato.com/ahmedabad/apna-fal-satellite/info",
"https://www.zomato.com/ahmedabad/tandoori-house-sector-21-gandhinagar/info",
"https://www.zomato.com/ahmedabad/swirl-vivanta-ahmedabad-sola/info",
"https://www.zomato.com/ahmedabad/spice-affair-hotel-german-palace-1-airport-gandhinagar-highway-gandhinagar/info",
"https://www.zomato.com/ahmedabad/no-great-shakes-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/riviera-restaurant-ashram-road/info",
"https://www.zomato.com/ahmedabad/caffix-the-tech-cafe-thaltej/info",
"https://www.zomato.com/ahmedabad/sachivalay-gymkhana-fast-food-corner-sector-21-gandhinagar/info",
"https://www.zomato.com/ahmedabad/kulcha-and-matka-chaat-hub-kmc-hub-mani-nagar/info",
"https://www.zomato.com/ahmedabad/the-belgian-waffle-co-bodakdev/info",
"https://www.zomato.com/ahmedabad/wki-we-knead-it-thaltej/info",
"https://www.zomato.com/ahmedabad/the-pink-door-by-ved-ventures-bopal/info",
"https://www.zomato.com/ahmedabad/saladific-thaltej/info",
"https://www.zomato.com/ahmedabad/ambrosia-restaurant-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/ten-11-lounge-cafe-restro-bodakdev/info",
"https://www.zomato.com/ahmedabad/camilo-coffee-thaltej/info",
"https://www.zomato.com/ahmedabad/khichdi-etc-1-navrangpura/info",
"https://www.zomato.com/ahmedabad/gopi-dalbati-gota/info",
"https://www.zomato.com/ahmedabad/from-the-bakers-table-bodakdev/info",
"https://www.zomato.com/ahmedabad/the-shake-maker-mani-nagar/info",
"https://www.zomato.com/ahmedabad/kulchas-more-nikol/info",
"https://www.zomato.com/ahmedabad/zodiac-fortune-select-sola/info",
"https://www.zomato.com/ahmedabad/london-yard-pizza-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/munching-moments-vasna/info",
"https://www.zomato.com/ahmedabad/jalaram-parotha-house-town-hall-walla-satellite/info",
"https://www.zomato.com/ahmedabad/biryani-badshah-kalupur/info",
"https://www.zomato.com/ahmedabad/the-gyan-cafe-gota/info",
"https://www.zomato.com/ahmedabad/prasang-2-sector-11-gandhinagar/info",
"https://www.zomato.com/ahmedabad/the-house-of-momos-mani-nagar/info",
"https://www.zomato.com/ahmedabad/mammas-kitchen-gota/info",
"https://www.zomato.com/ahmedabad/schezwan-kitchen-chandkheda/info",
"https://www.zomato.com/ahmedabad/yoohoo-bodakdev/info",
"https://www.zomato.com/ahmedabad/zikr-calcutte-ki-bopal/info",
"https://www.zomato.com/ahmedabad/urban-tandoor-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/chaat-king-bopal/info",
"https://www.zomato.com/ahmedabad/pleasure-trove-ashram-road/info",
"https://www.zomato.com/ahmedabad/hop-double-tree-by-hilton-bodakdev/info",
"https://www.zomato.com/ahmedabad/buonissimo-bodakdev/info",
"https://www.zomato.com/ahmedabad/prime-dine-restaurant-satellite/info",
"https://www.zomato.com/ahmedabad/hunnybun-satellite/info",
"https://www.zomato.com/ahmedabad/william-johns-pizza-1-bapunagar/info",
"https://www.zomato.com/ahmedabad/bhajiya-wale-nikol/info",
"https://www.zomato.com/ahmedabad/dev-chinese-point-frankie-roll-isanpur/info",
"https://www.zomato.com/ahmedabad/zarukhe-sg-road-gandhinagar/info",
"https://www.zomato.com/ahmedabad/the-daddy-chicken-hub-amraiwadi/info",
"https://www.zomato.com/ahmedabad/zodiac-fortune-landmark-ashram-road/info",
"https://www.zomato.com/ahmedabad/southern-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/aureate-el-dorado-navrangpura/info",
"https://www.zomato.com/ahmedabad/the-simply-salad-bodakdev/info",
"https://www.zomato.com/ahmedabad/brown-butter-bodakdev/info",
"https://www.zomato.com/ahmedabad/aunty-de-parathe-memnagar/info",
"https://www.zomato.com/ahmedabad/mumbai-on-plate-mani-nagar/info",
"https://www.zomato.com/ahmedabad/cravbit-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/coffee-by-di-bella-bodakdev/info",
"https://www.zomato.com/ahmedabad/café-farmland-bopal/info",
"https://www.zomato.com/ahmedabad/bluez-garden-cafe-restaurant-bopal/info",
"https://www.zomato.com/ahmedabad/regenta-inn-ranip-by-royal-orchid-hotels-ranip/info",
"https://www.zomato.com/ahmedabad/neem-dream-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/hotel-moti-mahal-sarkhej/info",
"https://www.zomato.com/ahmedabad/birmies-vastrapur/info",
"https://www.zomato.com/ahmedabad/shree-khodiyar-kathiyawadi-dhaba-satellite/info",
"https://www.zomato.com/ahmedabad/toska-chocolate-house-2-bodakdev/info",
"https://www.zomato.com/ahmedabad/xero-degrees-bodakdev/info",
"https://www.zomato.com/ahmedabad/moi-the-dessert-studio-bodakdev/info",
"https://www.zomato.com/ahmedabad/hedkey-nikol/info",
"https://www.zomato.com/ahmedabad/twisted-roots-2-bopal/info",
"https://www.zomato.com/ahmedabad/frankie-on-fire-navrangpura/info",
"https://www.zomato.com/ahmedabad/barbecue-culture-chandkheda/info",
"https://www.zomato.com/ahmedabad/legends-of-punjab-chandkheda/info",
"https://www.zomato.com/ahmedabad/sizzling-bbq-bodakdev/info",
"https://www.zomato.com/ahmedabad/martinoz-pizza-2-bopal/info",
"https://www.zomato.com/ahmedabad/mehfil-restaurant-paldi/info",
"https://www.zomato.com/ahmedabad/caferita-cafe-bopal/info",
"https://www.zomato.com/ahmedabad/urban-banjara-restro-cafe-bopal/info",
"https://www.zomato.com/ahmedabad/khana-khazana-24-carat-cafe-inder-residency-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/the-chocolate-room-4-chandkheda/info",
"https://www.zomato.com/ahmedabad/sambar-cafe-bopal/info",
"https://www.zomato.com/ahmedabad/super-donuts-the-american-eatery-bakery-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/pemdora-sola/info",
"https://www.zomato.com/ahmedabad/tulsi-patram-nikol/info",
"https://www.zomato.com/ahmedabad/p-bhagat-tarachand-mani-nagar/info",
"https://www.zomato.com/ahmedabad/lijjat-khaman-mani-nagar/info",
"https://www.zomato.com/ahmedabad/banjaraa-a-food-journey-bodakdev/info",
"https://www.zomato.com/ahmedabad/taranovas-pizza-memnagar/info",
"https://www.zomato.com/ahmedabad/cheers-bodakdev/info",
"https://www.zomato.com/ahmedabad/sandwichworkz-the-fusion-street-cafe-ambavadi/info",
"https://www.zomato.com/ahmedabad/dinng-momos-bao-2-mani-nagar/info",
"https://www.zomato.com/ahmedabad/greenz-restaurant-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/gardenia-fortune-park-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/la-minas-pizza-gota/info",
"https://www.zomato.com/ahmedabad/the-tent-cafe-navrangpura/info",
"https://www.zomato.com/ahmedabad/the-gir-vibes-kathiyawadi-bopal/info",
"https://www.zomato.com/ahmedabad/gopi-dining-hall-satellite/info",
"https://www.zomato.com/ahmedabad/rotlo-gujarati-rasthal-vastrapur/info",
"https://www.zomato.com/ahmedabad/new-capricorn-restaurant-naroda/info",
"https://www.zomato.com/ahmedabad/coffee-byus-ambavadi/info",
"https://www.zomato.com/ahmedabad/the-blue-oven-c-g-road/info",
"https://www.zomato.com/ahmedabad/shankars-ice-cream-library-bodakdev/info",
"https://www.zomato.com/ahmedabad/balan-dosa-chandkheda/info",
"https://www.zomato.com/ahmedabad/chai-shop-hyatt-regency-ashram-road/info",
"https://www.zomato.com/ahmedabad/iqbal-hotel-since-1947-jamalpur/info",
"https://www.zomato.com/ahmedabad/size-zero-cafe-restro-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/eminence-restaurant-and-banquet-naroda/info",
"https://www.zomato.com/ahmedabad/spirit-o-sound-chandkheda/info",
"https://www.zomato.com/ahmedabad/tesoro-cafe-bodakdev/info",
"https://www.zomato.com/ahmedabad/24-carat-cafe-inder-residency-ellis-bridge/info",
"https://www.zomato.com/ahmedabad/aangan-garden-restaurant-1-bopal/info",
"https://www.zomato.com/ahmedabad/bhavnaben-raval-sector-16-gandhinagar/info",
"https://www.zomato.com/ahmedabad/zen-cafe-satellite/info",
"https://www.zomato.com/ahmedabad/madhavrao-2-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/the-front-yard-satellite/info",
"https://www.zomato.com/ahmedabad/fayrouz-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/rps-pizzeria-1-bodakdev/info",
"https://www.zomato.com/ahmedabad/old-town-diner-sola/info",
"https://www.zomato.com/ahmedabad/bombay-darbar-biryani-rakhial/info",
"https://www.zomato.com/ahmedabad/momoman-infocity-gandhinagar/info",
"https://www.zomato.com/ahmedabad/detour-cafe-bopal/info",
"https://www.zomato.com/ahmedabad/dosawala-chandkheda/info",
"https://www.zomato.com/ahmedabad/memento-restaurant-and-banquet-ranip/info",
"https://www.zomato.com/ahmedabad/maruti-gujarati-thali-vastrapur/info",
"https://www.zomato.com/ahmedabad/happinezz-ice-creams-by-vadilal-prahlad-nagar/info",
"https://www.zomato.com/ahmedabad/the-mango-stories-naroda/info"
    # Add more URLs as needed
]

# Initialize lists to store data
all_data = []

for url in restaurant_urls:
    print(f"Fetching data from {url}...")
    restaurant_data = get_restaurant_data(url)
    if restaurant_data:
        all_data.append(restaurant_data)

# Create a DataFrame
df = pd.DataFrame(all_data)

# Save restaurant data to a CSV file
df.to_csv("restaurant_data.csv", index=False)

print("Data extraction complete. CSV file saved.")

